### ISSUE TITLE
Java Runtime Environment error when trying to launch GPS Action Replay from Velocitool

### ISSUE THREAD

**Issue by velocitek** [velocitek/Velocitool#7]
On some Macs, clicking the play button results in the error message: "To view this web content, you need to install the Java Runtime Environment." This message appears even when the Java Runtime Environment is installed and GPS Action Replay is working properly.

The problem seems to happen on newer Macs that came with Yosemite or El Capitan rather than older Macs that were updated to Yosemite or El Capitan.

Here is the workaround until we solve the problem:

1. Export your track from Velocitool as a GPX file.

2. Download Gsar "classic" from the bottom of this page: http://gpsactionreplay.free.fr/index.php?menu=2

3. Double click on gps.jar to launch GPS Action Replay.

4. In GPS Action Replay, select File>Open to open the GPX file you saved in step 1.

![screen shot 2016-02-12 at 2 36 41 pm](https://cloud.githubusercontent.com/assets/326087/13024684/ddf82a36-d19c-11e5-8a19-24f4d811e92f.png)

**Comment by moksamedia** [comment]
The best work around for this seems to be to create a Java bundle as outlined in [this](https://github.com/tofi86/universalJavaApplicationStub) link. It's also possible to embed the JRE used to launch the app, which could further minimize the chance of having Java runtime issues. I have created a working .app (both with the JRE bundled and not bundled). This new app bundle needs to be integrated into the Mac app & xcode project.

Time spent: 4 hours and 5 min.

**Comment by moksamedia** [comment]
Pushed commit with app-builder for GPS Action Replay. Still need to update README with some info on it, and look into code signing.

**Comment by moksamedia** [comment]
This should be fixed.
